### PR TITLE
add regex for date param in matches

### LINKED ISSUE #95: Matches endpoint errors when requesting by specifc match id
The matches endpoint for a specific match is currently broken.
E.g: `https://heroeslounge.gg/api/v1/matches/3122` => `http://localhost:8080/hl/api/v1/matches/312`

I expect to get information for the specified match, but instead instead get an error. I assume this an unforeseen side-effect from the update to the `matches/today` endpoint by @rogusdev

### PR DESCRIPTION
**Pull request by rogusdev**
Resolves #95

### CODE REVIEW

**Comment by Astraeus-** [comment]
Would it not have been more intuitive to define the endpoints as follows? 

`api/v1/matches/today/{tz1}/{tz2} ` defaulting to UTC 

`api/v1/matches/byDate/{date}/{tz1}/{tz2} ` defaulting to UTC

**Comment by rogusdev** [comment]
> Would it not have been more intuitive to define the endpoints as follows?
> 
> `api/v1/matches/today/{tz1}/{tz2} ` defaulting to UTC
> 
> `api/v1/matches/byDate/{date}/{tz1}/{tz2} ` defaulting to UTC

I could go either way.  Easy enough to change.

I still don't know where API docs are, so I don't know if they've been updated to communicate these new options yet anyway.  As in, I imagine we could still change things.

**Comment by Fabian-Sommer** [comment]
Currently, API docs are a link to the routes.php file (i.e. non-existent)

**Comment by rogusdev** [comment]
@Astraeus- you have my vote to change the endpoints if you want, @Fabian-Sommer pref?

**Comment by Fabian-Sommer** [comment]
No preference on my end

**Comment by Astraeus-** [comment]
I'll update them when I do the other API changes related to #72

**Pull request merged**
